//Header file for roaster controls functions
void IRAM_ATTR onRoastTimer();
void ProcessButtonRoastStart();
void ProcessMinButton_0();
void ProcessSecButton_0();
void ProcessPreMinButton_0();
void ProcessPreSecButton_0();
void ProcessPreTempButton();
void ProcessFinalTempButton();
void ProcessBeanQuantityButton();
void ProcessCoffeeType();
void ProcessRoastSettingsButton();
void UpdateSlider();
void ProcessButtonMixPwr();
void ProcessButtonMixDir();
void ProcessButtonHeaterPwr();
void ProcessButtonTimerStart();
void ProcessButtonTimerAdd();
void ProcessButtonTimerSub();
void ProcessPreheatTimerStart();
void ProcessStartPreHeat();
void readConfigData();
String SetRoastFilename();
void SetupRoastingLog();
void UpdateRoastingLog(bool first, bool last=false, bool stop=false);
void CloseRoastingLog(bool manualStop=false);
void SetupRoastTimer();
void ClearRoastTimer();
void DownloadConfigData();
void DownloadLogData();
//void IRAM_ATTR onPreHeatTimer();
